<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
    <Target Name="Create bundles" BeforeTargets="BeforeBuild">
    <Exec Command="npm install" WorkingDirectory="npmjs" />
    <Exec Command="npm run build" WorkingDirectory="npmjs"/>
  </Target>  
  <ItemGroup>
    <PackageReference Include="Logging.Memory" Version="3.1.0" />
    <PackageReference Include="ReactiveProperty" Version="9.7.0" />
    <PackageReference Include="System.IO.Ports" Version="9.0.1" />
  </ItemGroup>
</Project>